### ISSUE TITLE
Feature: Footer

### ISSUE THREAD

**Issue by aatng-gh** [chisafukutome/valencia-tech-club-website#3]

**Comment by doboianh** [comment]
Can i do it ?

**Comment by chisafukutome** [comment]
> Can i do it ?

Hey, I was just wondering how did you find this repo.?

**Comment by chisafukutome** [comment]
> Can i do it ?

Hi, sorry, we're restricting people who contribute to this project only to the club members. Could you please find other projects to work on ? Good luck on your next project!
