### ISSUE TITLE
Feature: Register button

### ISSUE THREAD

**Issue by aatng-gh** [chisafukutome/valencia-tech-club-website#5]
The button should link to [Engage](https://valenciacollege.campuslabs.com/engage/organization/valenciatechclub)

**Comment by NguyenLyy** [comment]
I want to do it. Can you guide me

**Comment by aatng-gh** [comment]
Of course!

To get started, you run these commands in your terminal. If you use Windows, use [Git Bash](https://gitforwindows.org/)
```bash
git clone https://github.com/chisafukutome/valencia-tech-club-website
cd valencia-tech-club-website
git checkout dev
git checkout -b feature-register-button
```

The file you will be working is `index/hero.html`, between the `<!-- Register button -->` and `<!-- End of Register button -->`
The documentation is [Button | Bulma](https://bulma.io/documentation/elements/button/)

Once you got this done, comment here. I will show you the next steps.

P/S: if you don't where the current directory is, run `pwd`

**Comment by chisafukutome** [comment]
> I want to do it. Can you guide me

I was just wondering, how did you find this repo.? is the link shared somewhere?

**Comment by chisafukutome** [comment]
> I want to do it. Can you guide me
Hi, sorry, we're restricting people who contribute to this project only to the club members. Could you please find other projects to work on ?

**Comment by fruitloops19** [comment]
yessssssss, lets gooooo
